import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../public/components/NavBar";
import SideNavBar from "../public/components/SideNavBar";
import NextTopLoader from 'nextjs-toploader';
import {UserProvider} from "@/public/UserContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <NextTopLoader color="#246d3c" showSpinner={false} />
        <NavBar />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
          <div className="flex   ">
            {/* Sidebar */}
                  <SideNavBar   />

            {/* Main content */}
            <main className="flex-1 p-4 border-l border-gray-500">
              {children}
            </main>
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
